# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI and Deployment to GitHub Pages

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 21.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: web/package-lock.json
    - run: cd web && npm ci
    - run: cd web && npm run build
    # - run: cd web && npm test # Optionally re-enable tests when ready.
    - name: Deploy to GitHub Pages
      run: cd web && npm run deploy
      env:
        NODE_ENV: production
        # This token is required to push changes to the gh-pages branch.
        # GITHUB_TOKEN is provided by Actions, you don't need to manually set it.
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

